version: "3"

services:
  cron:
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - 80:80
    links:
      - db
    environment:
      DATABASE: automacao_instagram # Inital database
      USER: admin # New User
      HOST: db
      PORT: 3306
      PASSWORD: 7WAE1#Ofne1 # New User Passwd
    volumes:
      - .:/usr/cron
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7WAE1#Ofne1 # root passwd
      MYSQL_DATABASE: automacao_instagram # Inital database
      MYSQL_USER: admin # New User
      MYSQL_PASSWORD: 7WAE1#Ofne1 # New User Passwd
      # MYSQL_RANDOM_ROOT_PASSWORD: "1" # Passwd random for root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
